# Four V100s, four local determinant walkers per device.
jax:
  enable_x64: true

workflow:
  batch_size: 16

subspace:
  evaluation:
    vmap_chunk_size: 1
    pair_chunk_size: 1

train:
  grads:
    vmap_chunk_size: 1

estimators:
  energy:
    kinetic:
      vmap_chunk_size: 1
