[tox]
requires =
    tox>=4.2
# lowest includes jax 0.4.36 as well as all other dependencies in lowest version
env_list =
    py312-lowest
    py312-jax{0.5.3, 0.6.2, 0.7.2, 0.8.2, 0.9.1}

[testenv]
runner = uv-venv-runner
package = editable
deps =
    jax0.5.3: jax==0.5.3
    jax0.6.2: jax==0.6.2
    jax0.7.2: jax==0.7.2
    jax0.8.2: jax==0.8.2
    jax0.9.1: jax==0.9.1
pass_env =
    *
commands =
    pytest -v {posargs}
constrain_package_deps = true
dependency_groups = test
uv_resolution =
    lowest: lowest-direct

[testenv:py312-docs]
deps =
    jax==0.9.1
dependency_groups = docs
commands =
    sphinx-build -W -b html docs docs/_build/html {posargs}
