# ===============================
# O atom
# ===============================

run_O_ccecp:
	python run.py --config configs/ecp/X.py:O,2,0,4,2,ccecp \
	--config.batch_size 128 \
	--config.optim.iterations 1000 \
	--config.log.save_path=O_ccecp \
	--config.log.restore_path=O_ccecp


# ===============================
# Sc atom
# ===============================

run_Sc_ccecp:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_ccecp \
	--config.log.restore_path=Sc_ccecp

run_Sc_tr2:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr2 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr2 \
	--config.log.restore_path=Sc_tr2

run_Sc_tr3:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr3 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr3 \
	--config.log.restore_path=Sc_tr3

run_Sc_tr4:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr4 \
	--config.log.restore_path=Sc_tr4

run_Sc_tr5:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr5 \
	--config.log.restore_path=Sc_tr5

run_Sc_tr6:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr6 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr6 \
	--config.log.restore_path=Sc_tr6

run_Sc_tr7:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr7 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr7 \
	--config.log.restore_path=Sc_tr7


# ===============================
# Sc atom (PH potentials)
# ===============================

run_Sc_l2:
	python run.py --config configs/ph/X.py:Sc,1,l2,0,6,5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_l2 \
	--config.log.restore_path=Sc_l2

run_Sc_hybrid:
	python run.py --config configs/ph/X.py:Sc,1,hybrid,0,6,5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_hybrid \
	--config.log.restore_path=Sc_hybrid


# ===============================
# Sc+ ion
# ===============================

run_Scplus_ccecp:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_ccecp \
	--config.log.restore_path=Scplus_ccecp

run_Scplus_tr2:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr2 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr2 \
	--config.log.restore_path=Scplus_tr2

run_Scplus_tr3:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr3 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr3 \
	--config.log.restore_path=Scplus_tr3

run_Scplus_tr4:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr4 \
	--config.log.restore_path=Scplus_tr4

run_Scplus_tr5:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr5 \
	--config.log.restore_path=Scplus_tr5

run_Scplus_tr6:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr6 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr6 \
	--config.log.restore_path=Scplus_tr6

run_Scplus_tr7:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr7 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr7 \
	--config.log.restore_path=Scplus_tr7


# ===============================
# Sc+ ion (PH potentials)
# ===============================

run_Scplus_l2:
	python run.py --config configs/ph/X.py:Sc,2,l2,1,6,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_l2 \
	--config.log.restore_path=Scplus_l2

run_Scplus_hybrid:
	python run.py --config configs/ph/X.py:Sc,2,hybrid,1,6,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_hybrid \
	--config.log.restore_path=Scplus_hybrid


# ===============================
# ScO molecule
# ===============================

run_ScO_ccecp:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_ccecp \
	--config.log.restore_path=ScO_ccecp

run_ScO_tr2:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr2 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr2 \
	--config.log.restore_path=ScO_tr2

run_ScO_tr3:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr3 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr3 \
	--config.log.restore_path=ScO_tr3

run_ScO_tr4:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr4 \
	--config.log.restore_path=ScO_tr4

run_ScO_tr5:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr5 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr5 \
	--config.log.restore_path=ScO_tr5

run_ScO_tr6:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr6 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr6 \
	--config.log.restore_path=ScO_tr6

run_ScO_tr7:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr7 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_tr7 \
	--config.log.restore_path=ScO_tr7


# ===============================
# ScO molecule (PH potentials)
# ===============================

run_ScO_l2:
	python run.py --config configs/ph/XO.py:Sc,1.664,1,l2,0,6,5,4,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_l2 \
	--config.log.restore_path=ScO_l2

run_ScO_hybrid:
	python run.py --config configs/ph/XO.py:Sc,1.664,1,hybrid,0,6,5,4,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_hybrid \
	--config.log.restore_path=ScO_hybrid