# ===============================
# O atom (All Electron)
# ===============================

run_O_all:
	python run.py --config configs/ecp/X.py:O,2,0,5,3,none \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=O_all \
	--config.log.restore_path=O_all


# ===============================
# Sc atom (ECP potentials)
# ===============================

run_Sc_ccecp:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_ccecp \
	--config.log.restore_path=Sc_ccecp

run_Sc_tr2:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr2 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr2 \
	--config.log.restore_path=Sc_tr2

run_Sc_tr3:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr3 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr3 \
	--config.log.restore_path=Sc_tr3

run_Sc_tr4:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr4 \
	--config.log.restore_path=Sc_tr4

run_Sc_tr5:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr5 \
	--config.log.restore_path=Sc_tr5

run_Sc_tr6:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr6 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr6 \
	--config.log.restore_path=Sc_tr6

run_Sc_tr7:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr7 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_tr7 \
	--config.log.restore_path=Sc_tr7


# ===============================
# Sc atom (PH / HPH potentials)
# ===============================

run_Sc_l2:
	python run.py --config configs/ph/X.py:Sc,1,0,6,5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_l2 \
	--config.log.restore_path=Sc_l2

run_Sc_hybrid:
	python run.py --config configs/hph/Sc.py:Sc,1,0,6,5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Sc_hybrid \
	--config.log.restore_path=Sc_hybrid


# ===============================
# Sc+ ion (ECP potentials)
# ===============================

run_Scplus_ccecp:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_ccecp \
	--config.log.restore_path=Scplus_ccecp

run_Scplus_tr2:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr2 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr2 \
	--config.log.restore_path=Scplus_tr2

run_Scplus_tr3:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr3 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr3 \
	--config.log.restore_path=Scplus_tr3

run_Scplus_tr4:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr4 \
	--config.log.restore_path=Scplus_tr4

run_Scplus_tr5:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr5 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr5 \
	--config.log.restore_path=Scplus_tr5

run_Scplus_tr6:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr6 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr6 \
	--config.log.restore_path=Scplus_tr6

run_Scplus_tr7:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr7 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_tr7 \
	--config.log.restore_path=Scplus_tr7


# ===============================
# Sc+ ion (PH / HPH potentials)
# ===============================

run_Scplus_l2:
	python run.py --config configs/ph/X.py:Sc,2,1,6,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_l2 \
	--config.log.restore_path=Scplus_l2

run_Scplus_hybrid:
	python run.py --config configs/hph/Sc.py:Sc,2,1,6,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=Scplus_hybrid \
	--config.log.restore_path=Scplus_hybrid


# ===============================
# S atom
# ===============================

run_S_l2:
	python run.py --config configs/ph/X.py:S,2,0,4,2 \
	--config.batch_size 4096 \
	--config.optim.iterations 30000 \
	--config.log.save_path=S_l2 \
	--config.log.restore_path=S_l2


# ===============================
# ScO molecule (2 atoms)
# ===============================

run_ScO_ccecp:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,ccecp \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_ccecp \
	--config.log.restore_path=ScO_ccecp

run_ScO_l2:
	python run.py --config configs/ph/XO.py:Sc,1.664,1,0,6,5,4,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_l2 \
	--config.log.restore_path=ScO_l2

run_ScO_hybrid:
	python run.py --config configs/hph/ScO.py:Sc,1.664,1,0,6,5,4,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScO_hybrid \
	--config.log.restore_path=ScO_hybrid


# ===============================
# ScS molecule (2 atoms)
# ===============================

run_ScS_hybrid:
	python run.py --config configs/hph/ScS.py:Sc,2.14,1,0,6,5,3,3 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=ScS_hybrid \
	--config.log.restore_path=ScS_hybrid


# ===============================
# SO molecule (2 atoms)
# ===============================

run_SO_l2:
	python run.py --config configs/ph/XO.py:S,1.48,2,0,4,2,4,4 \
	--config.batch_size 4096 \
	--config.optim.iterations 100000 \
	--config.log.save_path=SO_l2 \
	--config.log.restore_path=SO_l2