# ===============================
# O atom
# X.py input:
#   symbol,spin,charge,Xup,Xdn,ecps
# ===============================

O_ccecp:
	python run.py --config configs/ecp/X.py:O,2,0,4,2,ccecp --config.batch_size 128 --config.optim.iterations 1000


# ===============================
# Sc atom
# X.py input:
#   symbol,spin,charge,Xup,Xdn,ecps
# ===============================

Sc_ccecp:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,ccecp --config.batch_size 4096 --config.optim.iterations 30000

Sc_tr2:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr2 --config.batch_size 128 --config.optim.iterations 1000
Sc_tr3:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr3 --config.batch_size 4096 --config.optim.iterations 30000
Sc_tr4:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr4 --config.batch_size 4096 --config.optim.iterations 30000
Sc_tr5:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr5 --config.batch_size 4096 --config.optim.iterations 30000
Sc_tr6:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr6 --config.batch_size 4096 --config.optim.iterations 30000
Sc_tr7:
	python run.py --config configs/ecp/X.py:Sc,1,0,6,5,tr7 --config.batch_size 4096 --config.optim.iterations 30000


# ===============================
# Sc atom PH
# X.py input:
#   symbol,spin,pp_type,charge,Xup,Xdn,ecps
# ===============================

Sc_ph_l2:
	python run.py --config configs/ecp/X.py:Sc,1,l2,0,6,5,ccecp --config.batch_size 4096 --config.optim.iterations 30000

Sc_ph_hybrid:
	python run.py --config configs/ecp/X.py:Sc,1,hybrid,0,6,5,nl --config.batch_size 4096 --config.optim.iterations 30000


# ===============================
# Sc+ ion
# X.py input:
#   symbol,spin,charge,Xup,Xdn,ecps
# ===============================

Scplus_ccecp:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,ccecp --config.batch_size 4096 --config.optim.iterations 30000

Scplus_tr2:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr2 --config.batch_size 4096 --config.optim.iterations 30000
Scplus_tr3:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr3 --config.batch_size 4096 --config.optim.iterations 30000
Scplus_tr4:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr4 --config.batch_size 128 --config.optim.iterations 1000
Scplus_tr5:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr5 --config.batch_size 4096 --config.optim.iterations 30000
Scplus_tr6:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr6 --config.batch_size 4096 --config.optim.iterations 30000
Scplus_tr7:
	python run.py --config configs/ecp/X.py:Sc,2,1,6,4,tr7 --config.batch_size 4096 --config.optim.iterations 30000


# ===============================
# Sc+ ion PH
# X.py input:
#   symbol,spin,pp_type,charge,Xup,Xdn,ecps
# ===============================

Scplus_ph_l2:
	python run.py --config configs/ecp/X.py:Sc,2,l2,1,6,4,ccecp --config.batch_size 4096 --config.optim.iterations 30000

Scplus_ph_hybrid:
	python run.py --config configs/ecp/X.py:Sc,2,hybrid,1,6,4,nl --config.batch_size 4096 --config.optim.iterations 30000


# ===============================
# ScO molecule
# XO.py input:
#   symbol,dist,spin,charge,Xup,Xdn,Oup,Odn,ecps
# ===============================

ScO_ccecp:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,ccecp --config.batch_size 4096 --config.optim.iterations 100000

ScO_tr2:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr2 --config.batch_size 128 --config.optim.iterations 1000
ScO_tr3:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr3 --config.batch_size 4096 --config.optim.iterations 100000
ScO_tr4:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr4 --config.batch_size 4096 --config.optim.iterations 100000
ScO_tr5:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr5 --config.batch_size 4096 --config.optim.iterations 100000
ScO_tr6:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr6 --config.batch_size 4096 --config.optim.iterations 100000
ScO_tr7:
	python run.py --config configs/ecp/XO.py:Sc,1.664,1,0,6,5,4,4,tr7 --config.batch_size 4096 --config.optim.iterations 100000