jax:
  enable_x64: true
  default_matmul_precision: highest

system:
  rs: 1.0
  nspins: [7, 7]
  twist: [0.0, 0.0, 0.0]

workflow:
  seed: 42
  batch_size: 4096
  save_path: ./runs/heg_n14_rs1_train

wf:
  hidden_dims_single: [256, 256, 256, 256]
  hidden_dims_double: [32, 32, 32, 32]
  ndets: 16
  distance_type: tri
  full_det: true
  parameter_dtype: float64

sampler:
  steps: 20
  initial_width: 0.02
  pmove_range: [0.5, 0.6]

estimators:
  energy:
    kinetic:
      mode: forward_laplacian

pretrain:
  run:
    iterations: 1000

train:
  optim:
    learning_rate:
      rate: 0.03
    damping: 0.001
    norm_constraint: 0.001
  run:
    iterations: 200000
    save_time_interval: 600
    save_step_interval: 1000
